openapi: 3.0.0
info:
  title: Settle endpoint for Settlement Agency
  description: Settle API Specification
  version: 0.1.0-draft
security:
  - SubscriberAuth: []
externalDocs:
  description: Decentralized reconciliation and settlement process flow
  url: https://github.com/Open-network-for-digital-commerce/protocol-network-extension/blob/main/docs/draft/RSP-flow.pdf
paths:
  /settle:
    post:
      tags:
        - SettlementAgency
      description: settlement of payment for different receivers - called by RSP (Step 2a)
      requestBody:
        description: RSP asking settlement agency to settle receiver payments
        content:
          application/json:
            schema:
              type: object
              properties:
                context:
                  $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/draft/core/v0/api/core.yaml#/components/schemas/Context'
                message:
                  type: object
                  properties:
                    settlement:
                      $ref: '#/components/schemas/Settlement'
              required:
                - context
                - message
                - message.settlement.id
                - message.settlement.invoice_no
                - message.settlement.buyer_app_id
                - message.settlement.seller_app_id
                - message.settlement.settlement_id
                - message.settlement.settlement_details
      responses:
        '200':
          description: Acknowledgement of message received
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    properties:
                      ack:
                        $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/draft/core/v0/api/core.yaml#/components/schemas/Ack'
                    required:
                      - ack
                  error:
                    $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/draft/core/v0/api/core.yaml#/components/schemas/Error'
                required:
                  - message

components:
  securitySchemes:
    SubscriberAuth:
      type: apiKey
      in: header
      name: Authorization
      description: 'Signature of message body using Buyer App or Seller App subscriber''s signing public key. <br/><br/>Format:<br/><br/><code>Authorization : Signature keyId="{subscriber_id}|{unique_key_id}|{algorithm}",algorithm="ed25519",created="1606970629",expires="1607030629",headers="(created) (expires) digest",signature="Base64(signing string)"</code>'
  schemas:
    payout_metadata:
      description: Settlement bank Details for the payout
      type: object
      required:
        - payer_account_no
        - amount
        - time
        - payee_name
        - payee_account_no
        - payee_bank_code
        - payment_type
        - purpose_code
        - payee_account_type
      properties:
        payer_account_no:
          type: number
          description: "Debit Account Number of the client. This field is used when client maintains multiple debit account number with Bank."
        amount:
          $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/draft/core/v0/api/core.yaml#/components/schemas/Price'
        time:
          $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/draft/core/v0/api/core.yaml#/components/schemas/Time'
        payee_name:
          type: string
          description: "Payee name. Except for . @ ! , : |~ - _ # & /  no other special characters are accepted"
          example: "A to Z Printing Solutions Pvt. Ltd"
        payee_address:
          $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/draft/core/v0/api/core.yaml#/components/schemas/Address'
        payee_account_no:
          type: string
          description: "The account number of the beneficiary in which credit is to be given. Without Specail charcters and can be alpha numeric"
        payee_bank_code:
          type:  string
          description: "Bank Code of Payee e.g. IFSC code"
        payee_virtual_payment_address:
          type: string
          pattern: '^([a-zA-Z0-9]{2,10})@([a-zA-Z0-9]{2,10})'
        payment_type:
          type: string
          description: "This is the payment type allocated by the bank"
          enum:
            - RTGS
            - NEFT
            - IMPFS
            - IFT
            - UPI
        purpose_code:
          type: string
          maxLength: 10
          description: "For RTGS / IFT transaction it should contain CMS and for NEFT it should be OTH"
          enum:
            - CMS
            - OTH
        payee_account_type:
          type: string
          description: "Type of Beneficiary Account"
          enum:
           - 10
           - 11
           - 12
           - 13
           - 14
        remarks:
          $ref: 'https://raw.githubusercontent.com/beckn/protocol-specifications/draft/core/v0/api/core.yaml#/components/schemas/Descriptor'
    Settlement:
      description: Settlement details
      type: object
      properties:
        settlements:
          type: array
          items:
            type: object
            properties:
              payout_metadata:
                $ref: '#/components/schemas/payout_metadata'
              settlement_id:
                type: string
                description: "Unique identifier for each settlement"
                example: "121313"
              settlement_status:
                type: string
                enum:
                  - SETTLED
                  - PENDING
                  - ERROR
              settlement_reference_no:
                type: string
                description: "Reference number, incase of successful settlement"
                example: "3718683618631"
              error_message:
                type: object
                properties:
                  error_code:
                    type: string
                    description: "Error Message Code, to be provided by bank. Only required if settlement_status = error"
                    enum:
                      - "01"
                      - "02"
                      - "03"
                      - "04"
                  error_message:
                    type: string
                    description: Message for Failure/ error on settlement. Only required if settlement_status = error
                    example: "Account not active/ not found"
